var LevelData = [{
    comment: "level 1",
    parts: [{
        ysize: 800,
        objs: [{
            objname: "coin",
            x: 227,
            y: 50
        }, {
            objname: "coin",
            x: 160,
            y: 64
        }, {
            objname: "coin",
            x: 96,
            y: 81
        }, {
            objname: "coin",
            x: 49,
            y: 128
        }, {
            objname: "coin",
            x: 32,
            y: 192
        }, {
            objname: "ruby",
            x: 49,
            y: 256
        }, {
            objname: "coin",
            x: 96,
            y: 303
        }, {
            objname: "coin",
            x: 160,
            y: 320
        }, {
            objname: "coin",
            x: 224,
            y: 303
        }, {
            objname: "coin",
            x: 297,
            y: 279
        }, {
            objname: "coin",
            x: 369,
            y: 256
        }, {
            objname: "coin",
            x: 416,
            y: 209
        }, {
            objname: "coin",
            x: 480,
            y: 192
        }, {
            objname: "coin",
            x: 544,
            y: 209
        }, {
            objname: "coin",
            x: 591,
            y: 256
        }, {
            objname: "ruby",
            x: 608,
            y: 320
        }, {
            objname: "coin",
            x: 591,
            y: 384
        }, {
            objname: "coin",
            x: 544,
            y: 431
        }, {
            objname: "coin",
            x: 480,
            y: 448
        }, {
            objname: "coin",
            x: 397,
            y: 436
        }, {
            objname: "coin",
            x: 320,
            y: 416
        }, {
            objname: "coin",
            x: 256,
            y: 433
        }, {
            objname: "coin",
            x: 209,
            y: 480
        }, {
            objname: "coin",
            x: 192,
            y: 544
        }, {
            objname: "coin",
            x: 209,
            y: 608
        }, {
            objname: "coin",
            x: 256,
            y: 655
        }, {
            objname: "coin",
            x: 320,
            y: 672
        }, {
            objname: "coin",
            x: 364,
            y: 721
        }, {
            objname: "ruby",
            x: 370,
            y: 786
        }]
    }, {
        ysize: 320,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 256
        }]
    }]
}, {
    comment: "level 2",
    parts: [{
        ysize: 320,
        objs: [{
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 112,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 300
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 0
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 111,
            angle: 30
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 60
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 120
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 111,
            angle: 150
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 180
        }, {
            objname: "coin",
            x: 320,
            y: 160,
            movetype: "circ",
            radius: 64,
            angle: 240
        }, {
            objname: "ruby",
            x: 320,
            y: 160
        }, {
            objname: "mine",
            x: 32,
            y: 160
        }, {
            objname: "mine",
            x: 608,
            y: 160
        }]
    }, {
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 256,
            y: 208
        }, {
            objname: "coin",
            x: 320,
            y: 208
        }, {
            objname: "coin",
            x: 384,
            y: 208
        }, {
            objname: "coin",
            x: 416,
            y: 264
        }, {
            objname: "coin",
            x: 448,
            y: 320
        }, {
            objname: "coin",
            x: 416,
            y: 376
        }, {
            objname: "coin",
            x: 384,
            y: 432
        }, {
            objname: "coin",
            x: 320,
            y: 432
        }, {
            objname: "coin",
            x: 256,
            y: 432
        }, {
            objname: "coin",
            x: 224,
            y: 376
        }, {
            objname: "coin",
            x: 192,
            y: 320
        }, {
            objname: "coin",
            x: 224,
            y: 264
        }, {
            objname: "coin",
            x: 288,
            y: 264
        }, {
            objname: "coin",
            x: 352,
            y: 264
        }, {
            objname: "coin",
            x: 384,
            y: 320
        }, {
            objname: "coin",
            x: 352,
            y: 376
        }, {
            objname: "coin",
            x: 288,
            y: 376
        }, {
            objname: "coin",
            x: 256,
            y: 320
        }, {
            objname: "ruby",
            x: 320,
            y: 320
        }, {
            objname: "mine",
            x: 320,
            y: 608
        }, {
            objname: "mine",
            x: 32,
            y: 320
        }, {
            objname: "mine",
            x: 320,
            y: 32
        }, {
            objname: "mine",
            x: 608,
            y: 320
        }]
    }, {
        ysize: 480,
        objs: [{
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 112,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 300
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 0
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 111,
            angle: 30
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 60
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 120
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 111,
            angle: 150
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 180
        }, {
            objname: "coin",
            x: 320,
            y: 240,
            movetype: "circ",
            radius: 64,
            angle: 240
        }, {
            objname: "ruby",
            x: 320,
            y: 240
        }]
    }, {
        ysize: 320,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 256
        }]
    }]
}, {
    comment: "level 3",
    parts: [{
        ysize: 640,
        objs: [{
            objname: "mine",
            x: 320,
            y: 94
        }, {
            objname: "coin",
            x: 433,
            y: 207
        }, {
            objname: "mine",
            x: 546,
            y: 320
        }, {
            objname: "coin",
            x: 207,
            y: 207
        }, {
            objname: "ruby",
            x: 320,
            y: 320
        }, {
            objname: "coin",
            x: 433,
            y: 433
        }, {
            objname: "mine",
            x: 94,
            y: 320
        }, {
            objname: "coin",
            x: 207,
            y: 433
        }, {
            objname: "mine",
            x: 320,
            y: 546
        }]
    }, {
        ysize: 480,
        objs: [{
            objname: "coin",
            x: 464,
            y: 240
        }, {
            objname: "coin",
            x: 422,
            y: 342
        }, {
            objname: "coin",
            x: 320,
            y: 384
        }, {
            objname: "coin",
            x: 218,
            y: 342
        }, {
            objname: "coin",
            x: 176,
            y: 240
        }, {
            objname: "coin",
            x: 218,
            y: 138
        }, {
            objname: "coin",
            x: 320,
            y: 96
        }, {
            objname: "coin",
            x: 422,
            y: 138
        }, {
            objname: "squid",
            x: 560,
            y: 240
        }, {
            objname: "squid",
            x: 552,
            y: 302
        }, {
            objname: "squid",
            x: 528,
            y: 360
        }, {
            objname: "squid",
            x: 490,
            y: 410
        }, {
            objname: "squid",
            x: 150,
            y: 410
        }, {
            objname: "squid",
            x: 112,
            y: 360
        }, {
            objname: "squid",
            x: 88,
            y: 302
        }, {
            objname: "squid",
            x: 80,
            y: 240
        }, {
            objname: "squid",
            x: 88,
            y: 178
        }, {
            objname: "squid",
            x: 112,
            y: 120
        }, {
            objname: "squid",
            x: 150,
            y: 70
        }, {
            objname: "squid",
            x: 490,
            y: 70
        }, {
            objname: "squid",
            x: 528,
            y: 120
        }, {
            objname: "squid",
            x: 552,
            y: 178
        }, {
            objname: "ruby",
            x: 320,
            y: 240
        }]
    }, {
        ysize: 640,
        objs: [{
            objname: "mine",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 272,
            angle: 225
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 252
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 288
        }, {
            objname: "mine",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 272,
            angle: 315
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 198
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 91,
            angle: 225
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 91,
            angle: 315
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 342
        }, {
            objname: "ruby",
            x: 320,
            y: 320
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 162
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 91,
            angle: 135
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 91,
            angle: 45
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 18
        }, {
            objname: "mine",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 272,
            angle: 135
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 108
        }, {
            objname: "coin",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 202,
            angle: 72
        }, {
            objname: "mine",
            x: 316,
            y: 323,
            movetype: "circ",
            radius: 272,
            angle: 45
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 4",
    parts: [{
        ysize: 440,
        objs: [{
            objname: "stingray",
            x: 106,
            y: 80,
            movetype: "cirh",
            radius: 60,
            angle: 0
        }, {
            objname: "stingray",
            x: 320,
            y: 80,
            movetype: "cirh",
            radius: 60,
            angle: 10
        }, {
            objname: "stingray",
            x: 534,
            y: 80,
            movetype: "cirh",
            radius: 60,
            angle: 20
        }, {
            objname: "mine",
            x: 106,
            y: 240,
            movetype: "cirh",
            radius: 60,
            angle: 30
        }, {
            objname: "mine",
            x: 320,
            y: 240,
            movetype: "cirh",
            radius: 60,
            angle: 40
        }, {
            objname: "mine",
            x: 534,
            y: 240,
            movetype: "cirh",
            radius: 60,
            angle: 50
        }]
    }, {
        ysize: 540,
        objs: [{
            objname: "coin",
            x: 32,
            y: 207
        }, {
            objname: "coin",
            x: 96,
            y: 207
        }, {
            objname: "coin",
            x: 160,
            y: 207
        }, {
            objname: "coin",
            x: 224,
            y: 207
        }, {
            objname: "coin",
            x: 288,
            y: 207
        }, {
            objname: "coin",
            x: 352,
            y: 207
        }, {
            objname: "coin",
            x: 416,
            y: 207
        }, {
            objname: "coin",
            x: 480,
            y: 207
        }, {
            objname: "coin",
            x: 544,
            y: 207
        }, {
            objname: "coin",
            x: 608,
            y: 207
        }, {
            objname: "coin",
            x: 96,
            y: 271
        }, {
            objname: "coin",
            x: 160,
            y: 271
        }, {
            objname: "coin",
            x: 224,
            y: 271
        }, {
            objname: "coin",
            x: 288,
            y: 271
        }, {
            objname: "coin",
            x: 352,
            y: 271
        }, {
            objname: "coin",
            x: 416,
            y: 271
        }, {
            objname: "coin",
            x: 480,
            y: 271
        }, {
            objname: "coin",
            x: 544,
            y: 271
        }, {
            objname: "coin",
            x: 608,
            y: 271
        }, {
            objname: "coin",
            x: 96,
            y: 335
        }, {
            objname: "coin",
            x: 160,
            y: 335
        }, {
            objname: "coin",
            x: 224,
            y: 335
        }, {
            objname: "coin",
            x: 288,
            y: 335
        }, {
            objname: "coin",
            x: 352,
            y: 335
        }, {
            objname: "coin",
            x: 416,
            y: 335
        }, {
            objname: "coin",
            x: 480,
            y: 335
        }, {
            objname: "coin",
            x: 544,
            y: 335
        }, {
            objname: "coin",
            x: 608,
            y: 335
        }, {
            objname: "stingray",
            x: 32,
            y: 49
        }, {
            objname: "stingray",
            x: 320,
            y: 49
        }, {
            objname: "stingray",
            x: 608,
            y: 49
        }, {
            objname: "stingray",
            x: 32,
            y: 481
        }, {
            objname: "stingray",
            x: 320,
            y: 481
        }, {
            objname: "coin",
            x: 32,
            y: 271
        }, {
            objname: "coin",
            x: 32,
            y: 335
        }, {
            objname: "stingray",
            x: 608,
            y: 481
        }]
    }, {
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 252,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 182,
            angle: 258
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 126,
            angle: 234
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 180,
            angle: 210
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 252,
            angle: 198
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 180,
            angle: 186
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 126,
            angle: 162
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 181,
            angle: 138
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 252,
            angle: 126
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 181,
            angle: 114
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 126,
            angle: 90
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 181,
            angle: 66
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 252,
            angle: 54
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 181,
            angle: 42
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 126,
            angle: 18
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 179,
            angle: 354
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 251,
            angle: 342
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 180,
            angle: 330
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 125,
            angle: 306
        }, {
            objname: "coin",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 182,
            angle: 281
        }]
    }, {
        ysize: 448,
        objs: [{
            objname: "star",
            x: 160,
            y: 64
        }, {
            objname: "star",
            x: 224,
            y: 64
        }, {
            objname: "star",
            x: 288,
            y: 64
        }, {
            objname: "star",
            x: 352,
            y: 64
        }, {
            objname: "star",
            x: 416,
            y: 64
        }, {
            objname: "star",
            x: 480,
            y: 64
        }, {
            objname: "star",
            x: 160,
            y: 128
        }, {
            objname: "star",
            x: 224,
            y: 128
        }, {
            objname: "coin",
            x: 288,
            y: 128
        }, {
            objname: "coin",
            x: 352,
            y: 128
        }, {
            objname: "star",
            x: 416,
            y: 128
        }, {
            objname: "star",
            x: 480,
            y: 128
        }, {
            objname: "star",
            x: 160,
            y: 192
        }, {
            objname: "coin",
            x: 224,
            y: 192
        }, {
            objname: "ruby",
            x: 288,
            y: 192
        }, {
            objname: "ruby",
            x: 352,
            y: 192
        }, {
            objname: "coin",
            x: 416,
            y: 192
        }, {
            objname: "star",
            x: 480,
            y: 192
        }, {
            objname: "star",
            x: 160,
            y: 256
        }, {
            objname: "coin",
            x: 224,
            y: 256
        }, {
            objname: "ruby",
            x: 288,
            y: 256
        }, {
            objname: "ruby",
            x: 352,
            y: 256
        }, {
            objname: "coin",
            x: 416,
            y: 256
        }, {
            objname: "star",
            x: 480,
            y: 256
        }, {
            objname: "star",
            x: 160,
            y: 320
        }, {
            objname: "star",
            x: 224,
            y: 320
        }, {
            objname: "coin",
            x: 288,
            y: 320
        }, {
            objname: "coin",
            x: 352,
            y: 320
        }, {
            objname: "star",
            x: 416,
            y: 320
        }, {
            objname: "star",
            x: 480,
            y: 320
        }, {
            objname: "star",
            x: 160,
            y: 384
        }, {
            objname: "star",
            x: 224,
            y: 384
        }, {
            objname: "star",
            x: 288,
            y: 384
        }, {
            objname: "star",
            x: 352,
            y: 384
        }, {
            objname: "star",
            x: 416,
            y: 384
        }, {
            objname: "star",
            x: 480,
            y: 384
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 5",
    parts: [{
        ysize: 360,
        objs: [{
            objname: "coin",
            x: 200,
            y: 300
        }, {
            objname: "coin",
            x: 115,
            y: 265
        }, {
            objname: "coin",
            x: 80,
            y: 180
        }, {
            objname: "coin",
            x: 115,
            y: 95
        }, {
            objname: "coin",
            x: 200,
            y: 60
        }, {
            objname: "coin",
            x: 285,
            y: 95
        }, {
            objname: "coin",
            x: 320,
            y: 180
        }, {
            objname: "coin",
            x: 355,
            y: 265
        }, {
            objname: "coin",
            x: 440,
            y: 300
        }, {
            objname: "coin",
            x: 525,
            y: 265
        }, {
            objname: "coin",
            x: 560,
            y: 180
        }, {
            objname: "coin",
            x: 525,
            y: 95
        }, {
            objname: "coin",
            x: 440,
            y: 60
        }, {
            objname: "mine",
            x: 200,
            y: 180
        }, {
            objname: "mine",
            x: 440,
            y: 180
        }]
    }, {
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 160,
            y: 80
        }, {
            objname: "coin",
            x: 240,
            y: 160
        }, {
            objname: "coin",
            x: 320,
            y: 240
        }, {
            objname: "coin",
            x: 400,
            y: 320
        }, {
            objname: "coin",
            x: 480,
            y: 400
        }, {
            objname: "coin",
            x: 560,
            y: 480
        }, {
            objname: "coin",
            x: 80,
            y: 160
        }, {
            objname: "coin",
            x: 160,
            y: 240
        }, {
            objname: "coin",
            x: 240,
            y: 320
        }, {
            objname: "coin",
            x: 320,
            y: 400
        }, {
            objname: "coin",
            x: 400,
            y: 480
        }, {
            objname: "coin",
            x: 480,
            y: 560
        }, {
            objname: "mine",
            x: 160,
            y: 160
        }, {
            objname: "mine",
            x: 320,
            y: 320
        }, {
            objname: "mine",
            x: 480,
            y: 480
        }]
    }, {
        ysize: 600,
        objs: [{
            objname: "coin",
            x: 320,
            y: 180
        }, {
            objname: "coin",
            x: 285,
            y: 95
        }, {
            objname: "coin",
            x: 200,
            y: 60
        }, {
            objname: "coin",
            x: 115,
            y: 95
        }, {
            objname: "coin",
            x: 80,
            y: 180
        }, {
            objname: "coin",
            x: 115,
            y: 265
        }, {
            objname: "coin",
            x: 200,
            y: 300
        }, {
            objname: "coin",
            x: 115,
            y: 335
        }, {
            objname: "coin",
            x: 80,
            y: 420
        }, {
            objname: "coin",
            x: 115,
            y: 505
        }, {
            objname: "coin",
            x: 200,
            y: 540
        }, {
            objname: "coin",
            x: 285,
            y: 505
        }, {
            objname: "coin",
            x: 320,
            y: 420
        }, {
            objname: "coin",
            x: 355,
            y: 505
        }, {
            objname: "coin",
            x: 440,
            y: 540
        }, {
            objname: "coin",
            x: 525,
            y: 505
        }, {
            objname: "coin",
            x: 560,
            y: 420
        }, {
            objname: "coin",
            x: 525,
            y: 335
        }, {
            objname: "coin",
            x: 440,
            y: 300
        }, {
            objname: "coin",
            x: 525,
            y: 265
        }, {
            objname: "coin",
            x: 560,
            y: 180
        }, {
            objname: "coin",
            x: 525,
            y: 95
        }, {
            objname: "coin",
            x: 440,
            y: 60
        }, {
            objname: "coin",
            x: 355,
            y: 95
        }, {
            objname: "coin",
            x: 285,
            y: 265
        }, {
            objname: "coin",
            x: 355,
            y: 265
        }, {
            objname: "coin",
            x: 285,
            y: 335
        }, {
            objname: "coin",
            x: 355,
            y: 335
        }, {
            objname: "mine",
            x: 200,
            y: 180
        }, {
            objname: "mine",
            x: 440,
            y: 180
        }, {
            objname: "mine",
            x: 200,
            y: 420
        }, {
            objname: "mine",
            x: 440,
            y: 420
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "ruby",
            x: 160,
            y: 128
        }, {
            objname: "ruby",
            x: 320,
            y: 128
        }, {
            objname: "ruby",
            x: 480,
            y: 128
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 6",
    parts: [{
        ysize: 440,
        objs: [{
            objname: "coin",
            x: 440,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 0
        }, {
            objname: "coin",
            x: 405,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 45
        }, {
            objname: "coin",
            x: 320,
            y: 340,
            movetype: "circ",
            radius: 45,
            angle: 90
        }, {
            objname: "coin",
            x: 235,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 135
        }, {
            objname: "coin",
            x: 200,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 180
        }, {
            objname: "coin",
            x: 235,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 225
        }, {
            objname: "coin",
            x: 320,
            y: 100,
            movetype: "circ",
            radius: 45,
            angle: 270
        }, {
            objname: "coin",
            x: 405,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 315
        }, {
            objname: "mine",
            x: 32,
            y: 220
        }, {
            objname: "mine",
            x: 320,
            y: 220
        }, {
            objname: "mine",
            x: 608,
            y: 220
        }]
    }, {
        ysize: 440,
        objs: [{
            objname: "coin",
            x: 440,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 0
        }, {
            objname: "coin",
            x: 440,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 45
        }, {
            objname: "coin",
            x: 440,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 90
        }, {
            objname: "coin",
            x: 405,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 45
        }, {
            objname: "coin",
            x: 405,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 90
        }, {
            objname: "coin",
            x: 405,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 135
        }, {
            objname: "coin",
            x: 320,
            y: 340,
            movetype: "circ",
            radius: 45,
            angle: 90
        }, {
            objname: "coin",
            x: 320,
            y: 340,
            movetype: "circ",
            radius: 45,
            angle: 135
        }, {
            objname: "coin",
            x: 320,
            y: 340,
            movetype: "circ",
            radius: 45,
            angle: 180
        }, {
            objname: "coin",
            x: 235,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 135
        }, {
            objname: "coin",
            x: 235,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 180
        }, {
            objname: "coin",
            x: 235,
            y: 305,
            movetype: "circ",
            radius: 45,
            angle: 225
        }, {
            objname: "coin",
            x: 200,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 180
        }, {
            objname: "coin",
            x: 200,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 225
        }, {
            objname: "coin",
            x: 200,
            y: 220,
            movetype: "circ",
            radius: 45,
            angle: 270
        }, {
            objname: "coin",
            x: 235,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 225
        }, {
            objname: "coin",
            x: 235,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 270
        }, {
            objname: "coin",
            x: 235,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 315
        }, {
            objname: "coin",
            x: 320,
            y: 100,
            movetype: "circ",
            radius: 45,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 100,
            movetype: "circ",
            radius: 45,
            angle: 315
        }, {
            objname: "coin",
            x: 320,
            y: 100,
            movetype: "circ",
            radius: 45,
            angle: 0
        }, {
            objname: "coin",
            x: 405,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 315
        }, {
            objname: "coin",
            x: 405,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 0
        }, {
            objname: "coin",
            x: 405,
            y: 135,
            movetype: "circ",
            radius: 45,
            angle: 45
        }, {
            objname: "mine",
            x: 32,
            y: 220
        }, {
            objname: "mine",
            x: 320,
            y: 220
        }, {
            objname: "mine",
            x: 608,
            y: 220
        }]
    }, {
        ysize: 440,
        objs: [{
            objname: "mine",
            x: 176,
            y: 220
        }, {
            objname: "coin",
            x: 280,
            y: 220,
            movetype: "circ",
            radius: 40,
            angle: 0
        }, {
            objname: "coin",
            x: 250,
            y: 294,
            movetype: "circ",
            radius: 40,
            angle: 45
        }, {
            objname: "coin",
            x: 176,
            y: 324,
            movetype: "circ",
            radius: 40,
            angle: 90
        }, {
            objname: "coin",
            x: 102,
            y: 294,
            movetype: "circ",
            radius: 40,
            angle: 135
        }, {
            objname: "coin",
            x: 72,
            y: 220,
            movetype: "circ",
            radius: 40,
            angle: 180
        }, {
            objname: "coin",
            x: 102,
            y: 146,
            movetype: "circ",
            radius: 40,
            angle: 225
        }, {
            objname: "coin",
            x: 176,
            y: 116,
            movetype: "circ",
            radius: 40,
            angle: 270
        }, {
            objname: "coin",
            x: 250,
            y: 146,
            movetype: "circ",
            radius: 40,
            angle: 315
        }, {
            objname: "mine",
            x: 464,
            y: 220
        }, {
            objname: "coin",
            x: 568,
            y: 220,
            movetype: "circ",
            radius: 40,
            angle: 0
        }, {
            objname: "coin",
            x: 538,
            y: 294,
            movetype: "circ",
            radius: 40,
            angle: 45
        }, {
            objname: "coin",
            x: 464,
            y: 324,
            movetype: "circ",
            radius: 40,
            angle: 90
        }, {
            objname: "coin",
            x: 390,
            y: 294,
            movetype: "circ",
            radius: 40,
            angle: 135
        }, {
            objname: "coin",
            x: 360,
            y: 220,
            movetype: "circ",
            radius: 40,
            angle: 180
        }, {
            objname: "coin",
            x: 390,
            y: 146,
            movetype: "circ",
            radius: 40,
            angle: 225
        }, {
            objname: "coin",
            x: 464,
            y: 116,
            movetype: "circ",
            radius: 40,
            angle: 270
        }, {
            objname: "coin",
            x: 538,
            y: 146,
            movetype: "circ",
            radius: 40,
            angle: 315
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "ruby",
            x: 160,
            y: 128
        }, {
            objname: "ruby",
            x: 320,
            y: 128
        }, {
            objname: "ruby",
            x: 480,
            y: 128
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 7",
    parts: [{
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 261,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 207,
            angle: 261
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 207,
            angle: 279
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 162,
            angle: 247
        }, {
            objname: "ruby",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 149,
            angle: 270
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 162,
            angle: 293
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 134,
            angle: 224
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 98,
            angle: 251
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 98,
            angle: 289
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 134,
            angle: 316
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 133,
            angle: 196
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 133,
            angle: 344
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 161,
            angle: 173
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 98,
            angle: 169
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 161,
            angle: 7
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 206,
            angle: 159
        }, {
            objname: "ruby",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 148,
            angle: 150
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 99,
            angle: 130
        }, {
            objname: "ruby",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 148,
            angle: 30
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 206,
            angle: 21
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 259,
            angle: 150
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 207,
            angle: 141
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 162,
            angle: 126
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 135,
            angle: 104
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 162,
            angle: 54
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 207,
            angle: 39
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 259,
            angle: 30
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 98,
            angle: 11
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 99,
            angle: 50
        }, {
            objname: "coin",
            x: 320,
            y: 352,
            movetype: "circ",
            radius: 135,
            angle: 76
        }, {
            objname: "ruby",
            x: 320,
            y: 352
        }]
    }, {
        ysize: 728,
        objs: [{
            objname: "coin",
            x: 192,
            y: 140
        }, {
            objname: "coin",
            x: 256,
            y: 140
        }, {
            objname: "coin",
            x: 320,
            y: 140
        }, {
            objname: "coin",
            x: 384,
            y: 140
        }, {
            objname: "coin",
            x: 448,
            y: 140
        }, {
            objname: "coin",
            x: 480,
            y: 196
        }, {
            objname: "coin",
            x: 512,
            y: 252
        }, {
            objname: "coin",
            x: 544,
            y: 308
        }, {
            objname: "coin",
            x: 160,
            y: 196
        }, {
            objname: "coin",
            x: 224,
            y: 196
        }, {
            objname: "coin",
            x: 288,
            y: 196
        }, {
            objname: "coin",
            x: 352,
            y: 196
        }, {
            objname: "coin",
            x: 416,
            y: 196
        }, {
            objname: "coin",
            x: 448,
            y: 252
        }, {
            objname: "coin",
            x: 480,
            y: 308
        }, {
            objname: "coin",
            x: 512,
            y: 364
        }, {
            objname: "coin",
            x: 128,
            y: 252
        }, {
            objname: "coin",
            x: 192,
            y: 252
        }, {
            objname: "coin",
            x: 256,
            y: 252
        }, {
            objname: "coin",
            x: 320,
            y: 252
        }, {
            objname: "coin",
            x: 384,
            y: 252
        }, {
            objname: "coin",
            x: 416,
            y: 308
        }, {
            objname: "coin",
            x: 448,
            y: 364
        }, {
            objname: "coin",
            x: 480,
            y: 420
        }, {
            objname: "coin",
            x: 96,
            y: 308
        }, {
            objname: "coin",
            x: 160,
            y: 308
        }, {
            objname: "coin",
            x: 224,
            y: 308
        }, {
            objname: "coin",
            x: 224,
            y: 420
        }, {
            objname: "coin",
            x: 256,
            y: 476
        }, {
            objname: "coin",
            x: 320,
            y: 476
        }, {
            objname: "coin",
            x: 384,
            y: 476
        }, {
            objname: "coin",
            x: 416,
            y: 532
        }, {
            objname: "coin",
            x: 64,
            y: 364
        }, {
            objname: "coin",
            x: 128,
            y: 364
        }, {
            objname: "coin",
            x: 192,
            y: 364
        }, {
            objname: "coin",
            x: 192,
            y: 476
        }, {
            objname: "coin",
            x: 224,
            y: 532
        }, {
            objname: "coin",
            x: 288,
            y: 532
        }, {
            objname: "coin",
            x: 352,
            y: 532
        }, {
            objname: "coin",
            x: 384,
            y: 588
        }, {
            objname: "coin",
            x: 576,
            y: 364
        }, {
            objname: "coin",
            x: 96,
            y: 420
        }, {
            objname: "coin",
            x: 160,
            y: 420
        }, {
            objname: "coin",
            x: 160,
            y: 532
        }, {
            objname: "coin",
            x: 192,
            y: 588
        }, {
            objname: "coin",
            x: 256,
            y: 588
        }, {
            objname: "coin",
            x: 320,
            y: 588
        }, {
            objname: "coin",
            x: 448,
            y: 476
        }, {
            objname: "coin",
            x: 512,
            y: 476
        }, {
            objname: "mine",
            x: 320,
            y: 32
        }, {
            objname: "coin",
            x: 128,
            y: 476
        }, {
            objname: "mine",
            x: 608,
            y: 530
        }, {
            objname: "mine",
            x: 32,
            y: 198
        }, {
            objname: "mine",
            x: 32,
            y: 530
        }, {
            objname: "coin",
            x: 416,
            y: 420
        }, {
            objname: "mine",
            x: 320,
            y: 696
        }, {
            objname: "coin",
            x: 544,
            y: 420
        }, {
            objname: "coin",
            x: 480,
            y: 532
        }, {
            objname: "coin",
            x: 448,
            y: 588
        }, {
            objname: "mine",
            x: 608,
            y: 198
        }, {
            objname: "mine",
            x: 320,
            y: 364
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "ruby",
            x: 160,
            y: 128
        }, {
            objname: "ruby",
            x: 320,
            y: 128
        }, {
            objname: "ruby",
            x: 480,
            y: 128
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 8",
    parts: [{
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 279,
            y: 250
        }, {
            objname: "coin",
            x: 360,
            y: 250
        }, {
            objname: "coin",
            x: 240,
            y: 320
        }, {
            objname: "ruby",
            x: 320,
            y: 320
        }, {
            objname: "coin",
            x: 400,
            y: 320
        }, {
            objname: "coin",
            x: 280,
            y: 389
        }, {
            objname: "coin",
            x: 360,
            y: 389
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 200
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 220
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 240
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 260
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 280
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 300
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 20
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 40
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 60
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 80
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 100
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 280,
            angle: 120
        }]
    }, {
        ysize: 400,
        objs: [{
            objname: "coin",
            x: 49,
            y: 137
        }, {
            objname: "coin",
            x: 61,
            y: 106
        }, {
            objname: "coin",
            x: 91,
            y: 92
        }, {
            objname: "coin",
            x: 121,
            y: 106
        }, {
            objname: "coin",
            x: 135,
            y: 136
        }, {
            objname: "coin",
            x: 133,
            y: 167
        }, {
            objname: "coin",
            x: 119,
            y: 197
        }, {
            objname: "coin",
            x: 99,
            y: 223
        }, {
            objname: "coin",
            x: 79,
            y: 249
        }, {
            objname: "coin",
            x: 60,
            y: 276
        }, {
            objname: "coin",
            x: 48,
            y: 307
        }, {
            objname: "coin",
            x: 80,
            y: 307
        }, {
            objname: "coin",
            x: 112,
            y: 307
        }, {
            objname: "coin",
            x: 144,
            y: 307
        }, {
            objname: "coin",
            x: 274,
            y: 108
        }, {
            objname: "coin",
            x: 285,
            y: 138
        }, {
            objname: "coin",
            x: 287,
            y: 170
        }, {
            objname: "coin",
            x: 289,
            y: 200
        }, {
            objname: "coin",
            x: 287,
            y: 229
        }, {
            objname: "coin",
            x: 285,
            y: 261
        }, {
            objname: "coin",
            x: 274,
            y: 291
        }, {
            objname: "coin",
            x: 245,
            y: 307
        }, {
            objname: "coin",
            x: 216,
            y: 291
        }, {
            objname: "coin",
            x: 205,
            y: 261
        }, {
            objname: "coin",
            x: 203,
            y: 229
        }, {
            objname: "coin",
            x: 201,
            y: 200
        }, {
            objname: "coin",
            x: 203,
            y: 170
        }, {
            objname: "coin",
            x: 205,
            y: 138
        }, {
            objname: "coin",
            x: 216,
            y: 108
        }, {
            objname: "coin",
            x: 245,
            y: 92
        }, {
            objname: "coin",
            x: 367,
            y: 142
        }, {
            objname: "coin",
            x: 388,
            y: 116
        }, {
            objname: "coin",
            x: 409,
            y: 92
        }, {
            objname: "coin",
            x: 409,
            y: 123
        }, {
            objname: "coin",
            x: 409,
            y: 154
        }, {
            objname: "coin",
            x: 409,
            y: 184
        }, {
            objname: "coin",
            x: 409,
            y: 215
        }, {
            objname: "coin",
            x: 409,
            y: 246
        }, {
            objname: "coin",
            x: 409,
            y: 276
        }, {
            objname: "coin",
            x: 409,
            y: 307
        }, {
            objname: "coin",
            x: 572,
            y: 307
        }, {
            objname: "coin",
            x: 572,
            y: 277
        }, {
            objname: "coin",
            x: 572,
            y: 246
        }, {
            objname: "coin",
            x: 572,
            y: 215
        }, {
            objname: "coin",
            x: 572,
            y: 184
        }, {
            objname: "coin",
            x: 572,
            y: 154
        }, {
            objname: "coin",
            x: 572,
            y: 123
        }, {
            objname: "coin",
            x: 572,
            y: 92
        }, {
            objname: "coin",
            x: 557,
            y: 123
        }, {
            objname: "coin",
            x: 539,
            y: 154
        }, {
            objname: "coin",
            x: 521,
            y: 184
        }, {
            objname: "coin",
            x: 503,
            y: 215
        }, {
            objname: "coin",
            x: 487,
            y: 246
        }, {
            objname: "coin",
            x: 540,
            y: 246
        }, {
            objname: "coin",
            x: 604,
            y: 246
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 9",
    parts: [{
        ysize: 544,
        objs: [{
            objname: "mine",
            x: 32,
            y: 128
        }, {
            objname: "mine",
            x: 104,
            y: 128
        }, {
            objname: "mine",
            x: 176,
            y: 128
        }, {
            objname: "mine",
            x: 248,
            y: 128
        }, {
            objname: "mine",
            x: 320,
            y: 128
        }, {
            objname: "mine",
            x: 320,
            y: 200
        }, {
            objname: "mine",
            x: 320,
            y: 272
        }, {
            objname: "mine",
            x: 320,
            y: 344
        }, {
            objname: "mine",
            x: 320,
            y: 416
        }, {
            objname: "mine",
            x: 392,
            y: 416
        }, {
            objname: "mine",
            x: 464,
            y: 416
        }, {
            objname: "mine",
            x: 536,
            y: 416
        }, {
            objname: "mine",
            x: 608,
            y: 416
        }, {
            objname: "coin",
            x: 463,
            y: 56
        }, {
            objname: "coin",
            x: 463,
            y: 128
        }, {
            objname: "coin",
            x: 482,
            y: 200
        }, {
            objname: "coin",
            x: 535,
            y: 253
        }, {
            objname: "coin",
            x: 607,
            y: 272
        }, {
            objname: "coin",
            x: 32,
            y: 272
        }, {
            objname: "coin",
            x: 104,
            y: 291
        }, {
            objname: "coin",
            x: 157,
            y: 344
        }, {
            objname: "coin",
            x: 176,
            y: 416
        }, {
            objname: "coin",
            x: 176,
            y: 488
        }]
    }, {
        ysize: 240,
        objs: [{
            objname: "squid",
            x: 320,
            y: 40,
            movetype: "cirh",
            radius: 250,
            angle: 0
        }, {
            objname: "squid",
            x: 320,
            y: 80,
            movetype: "cirh",
            radius: 250,
            angle: 10
        }, {
            objname: "squid",
            x: 320,
            y: 120,
            movetype: "cirh",
            radius: 250,
            angle: 20
        }, {
            objname: "squid",
            x: 320,
            y: 160,
            movetype: "cirh",
            radius: 250,
            angle: 30
        }, {
            objname: "squid",
            x: 320,
            y: 40,
            movetype: "cirh",
            radius: 250,
            angle: 180
        }, {
            objname: "squid",
            x: 320,
            y: 80,
            movetype: "cirh",
            radius: 250,
            angle: 190
        }, {
            objname: "squid",
            x: 320,
            y: 120,
            movetype: "cirh",
            radius: 250,
            angle: 200
        }, {
            objname: "squid",
            x: 320,
            y: 160,
            movetype: "cirh",
            radius: 250,
            angle: 210
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "ruby",
            x: 160,
            y: 128
        }, {
            objname: "ruby",
            x: 320,
            y: 128
        }, {
            objname: "ruby",
            x: 480,
            y: 128
        }]
    }, {
        ysize: 256,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 192
        }]
    }]
}, {
    comment: "level 10",
    parts: [{
        ysize: 720,
        objs: [{
            objname: "squid",
            x: 256,
            y: 32,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "squid",
            x: 320,
            y: 32,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "squid",
            x: 384,
            y: 32,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "coin",
            x: 32,
            y: 96
        }, {
            objname: "coin",
            x: 96,
            y: 96
        }, {
            objname: "coin",
            x: 160,
            y: 96
        }, {
            objname: "coin",
            x: 224,
            y: 96
        }, {
            objname: "coin",
            x: 288,
            y: 96
        }, {
            objname: "coin",
            x: 352,
            y: 96
        }, {
            objname: "coin",
            x: 416,
            y: 96
        }, {
            objname: "coin",
            x: 480,
            y: 96
        }, {
            objname: "coin",
            x: 544,
            y: 96
        }, {
            objname: "coin",
            x: 608,
            y: 96
        }, {
            objname: "coin",
            x: 32,
            y: 160
        }, {
            objname: "coin",
            x: 96,
            y: 160
        }, {
            objname: "coin",
            x: 160,
            y: 160
        }, {
            objname: "coin",
            x: 224,
            y: 160
        }, {
            objname: "coin",
            x: 288,
            y: 160
        }, {
            objname: "coin",
            x: 352,
            y: 160
        }, {
            objname: "coin",
            x: 416,
            y: 160
        }, {
            objname: "coin",
            x: 480,
            y: 160
        }, {
            objname: "coin",
            x: 544,
            y: 160
        }, {
            objname: "coin",
            x: 608,
            y: 160
        }, {
            objname: "squid",
            x: 256,
            y: 224,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }, {
            objname: "squid",
            x: 320,
            y: 224,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }, {
            objname: "squid",
            x: 384,
            y: 224,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }, {
            objname: "coin",
            x: 32,
            y: 288
        }, {
            objname: "coin",
            x: 96,
            y: 288
        }, {
            objname: "coin",
            x: 160,
            y: 288
        }, {
            objname: "coin",
            x: 224,
            y: 288
        }, {
            objname: "coin",
            x: 288,
            y: 288
        }, {
            objname: "coin",
            x: 352,
            y: 288
        }, {
            objname: "coin",
            x: 416,
            y: 288
        }, {
            objname: "coin",
            x: 480,
            y: 288
        }, {
            objname: "coin",
            x: 544,
            y: 288
        }, {
            objname: "coin",
            x: 608,
            y: 288
        }, {
            objname: "coin",
            x: 32,
            y: 352
        }, {
            objname: "coin",
            x: 96,
            y: 352
        }, {
            objname: "coin",
            x: 160,
            y: 352
        }, {
            objname: "coin",
            x: 224,
            y: 352
        }, {
            objname: "coin",
            x: 288,
            y: 352
        }, {
            objname: "coin",
            x: 352,
            y: 352
        }, {
            objname: "coin",
            x: 416,
            y: 352
        }, {
            objname: "coin",
            x: 480,
            y: 352
        }, {
            objname: "coin",
            x: 544,
            y: 352
        }, {
            objname: "coin",
            x: 608,
            y: 352
        }, {
            objname: "squid",
            x: 256,
            y: 416,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "squid",
            x: 320,
            y: 416,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "squid",
            x: 384,
            y: 416,
            movetype: "cirh",
            radius: 224,
            angle: 180
        }, {
            objname: "coin",
            x: 32,
            y: 480
        }, {
            objname: "coin",
            x: 96,
            y: 480
        }, {
            objname: "coin",
            x: 160,
            y: 480
        }, {
            objname: "coin",
            x: 224,
            y: 480
        }, {
            objname: "coin",
            x: 288,
            y: 480
        }, {
            objname: "coin",
            x: 352,
            y: 480
        }, {
            objname: "coin",
            x: 416,
            y: 480
        }, {
            objname: "coin",
            x: 480,
            y: 480
        }, {
            objname: "coin",
            x: 544,
            y: 480
        }, {
            objname: "coin",
            x: 608,
            y: 480
        }, {
            objname: "coin",
            x: 32,
            y: 544
        }, {
            objname: "coin",
            x: 96,
            y: 544
        }, {
            objname: "coin",
            x: 160,
            y: 544
        }, {
            objname: "coin",
            x: 224,
            y: 544
        }, {
            objname: "coin",
            x: 288,
            y: 544
        }, {
            objname: "coin",
            x: 352,
            y: 544
        }, {
            objname: "coin",
            x: 416,
            y: 544
        }, {
            objname: "coin",
            x: 480,
            y: 544
        }, {
            objname: "coin",
            x: 544,
            y: 544
        }, {
            objname: "coin",
            x: 608,
            y: 544
        }, {
            objname: "squid",
            x: 256,
            y: 608,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }, {
            objname: "squid",
            x: 320,
            y: 608,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }, {
            objname: "squid",
            x: 384,
            y: 608,
            movetype: "cirh",
            radius: 224,
            angle: 0
        }]
    }, {
        ysize: 640,
        objs: [{
            objname: "coin",
            x: 320,
            y: 133
        }, {
            objname: "coin",
            x: 288,
            y: 189
        }, {
            objname: "coin",
            x: 352,
            y: 189
        }, {
            objname: "coin",
            x: 256,
            y: 245
        }, {
            objname: "coin",
            x: 320,
            y: 245
        }, {
            objname: "coin",
            x: 384,
            y: 245
        }, {
            objname: "coin",
            x: 224,
            y: 301
        }, {
            objname: "coin",
            x: 416,
            y: 301
        }, {
            objname: "coin",
            x: 192,
            y: 357
        }, {
            objname: "coin",
            x: 256,
            y: 357
        }, {
            objname: "coin",
            x: 384,
            y: 357
        }, {
            objname: "coin",
            x: 448,
            y: 357
        }, {
            objname: "coin",
            x: 160,
            y: 413
        }, {
            objname: "coin",
            x: 224,
            y: 413
        }, {
            objname: "coin",
            x: 288,
            y: 413
        }, {
            objname: "coin",
            x: 352,
            y: 413
        }, {
            objname: "coin",
            x: 416,
            y: 413
        }, {
            objname: "coin",
            x: 480,
            y: 413
        }, {
            objname: "ruby",
            x: 320,
            y: 320
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 60
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 75
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 90
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 105
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 120
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 195
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 210
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 225
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 240
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 300
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 315
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 330
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "circ",
            radius: 288,
            angle: 345
        }]
    }, {
        ysize: 840,
        objs: [{
            objname: "coin",
            x: 256,
            y: 180
        }, {
            objname: "coin",
            x: 288,
            y: 236
        }, {
            objname: "coin",
            x: 320,
            y: 292
        }, {
            objname: "coin",
            x: 320,
            y: 356
        }, {
            objname: "coin",
            x: 320,
            y: 484
        }, {
            objname: "coin",
            x: 320,
            y: 548
        }, {
            objname: "coin",
            x: 288,
            y: 604
        }, {
            objname: "coin",
            x: 256,
            y: 660
        }, {
            objname: "coin",
            x: 320,
            y: 180
        }, {
            objname: "coin",
            x: 352,
            y: 236
        }, {
            objname: "ruby",
            x: 320,
            y: 420
        }, {
            objname: "mine",
            x: 179,
            y: 297
        }, {
            objname: "mine",
            x: 212,
            y: 354
        }, {
            objname: "mine",
            x: 224,
            y: 420
        }, {
            objname: "coin",
            x: 352,
            y: 604
        }, {
            objname: "coin",
            x: 320,
            y: 660
        }, {
            objname: "coin",
            x: 384,
            y: 180
        }, {
            objname: "mine",
            x: 212,
            y: 486
        }, {
            objname: "mine",
            x: 179,
            y: 543
        }, {
            objname: "mine",
            x: 461,
            y: 297
        }, {
            objname: "mine",
            x: 428,
            y: 354
        }, {
            objname: "mine",
            x: 416,
            y: 420
        }, {
            objname: "mine",
            x: 428,
            y: 486
        }, {
            objname: "coin",
            x: 384,
            y: 660
        }, {
            objname: "mine",
            x: 461,
            y: 543
        }]
    }, {
        ysize: 320,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 256
        }]
    }]
}, {
    comment: "level 11 prefinal",
    parts: [{
        ysize: 1280,
        objs: [{
            objname: "mine",
            x: 32,
            y: 288
        }, {
            objname: "mine",
            x: 96,
            y: 288
        }, {
            objname: "mine",
            x: 160,
            y: 288
        }, {
            objname: "mine",
            x: 224,
            y: 288
        }, {
            objname: "mine",
            x: 288,
            y: 288
        }, {
            objname: "mine",
            x: 352,
            y: 288
        }, {
            objname: "mine",
            x: 416,
            y: 288
        }, {
            objname: "mine",
            x: 224,
            y: 544
        }, {
            objname: "mine",
            x: 288,
            y: 544
        }, {
            objname: "mine",
            x: 352,
            y: 544
        }, {
            objname: "mine",
            x: 416,
            y: 544
        }, {
            objname: "mine",
            x: 480,
            y: 544
        }, {
            objname: "mine",
            x: 544,
            y: 544
        }, {
            objname: "mine",
            x: 608,
            y: 544
        }, {
            objname: "coin",
            x: 96,
            y: 32
        }, {
            objname: "coin",
            x: 113,
            y: 96
        }, {
            objname: "coin",
            x: 160,
            y: 143
        }, {
            objname: "coin",
            x: 224,
            y: 160
        }, {
            objname: "coin",
            x: 288,
            y: 160
        }, {
            objname: "coin",
            x: 352,
            y: 160
        }, {
            objname: "coin",
            x: 416,
            y: 160
        }, {
            objname: "coin",
            x: 480,
            y: 177
        }, {
            objname: "coin",
            x: 527,
            y: 224
        }, {
            objname: "ruby",
            x: 544,
            y: 288
        }, {
            objname: "coin",
            x: 527,
            y: 352
        }, {
            objname: "coin",
            x: 480,
            y: 399
        }, {
            objname: "coin",
            x: 416,
            y: 416
        }, {
            objname: "coin",
            x: 352,
            y: 416
        }, {
            objname: "coin",
            x: 288,
            y: 416
        }, {
            objname: "coin",
            x: 224,
            y: 416
        }, {
            objname: "coin",
            x: 158,
            y: 433
        }, {
            objname: "coin",
            x: 111,
            y: 480
        }, {
            objname: "ruby",
            x: 94,
            y: 544
        }, {
            objname: "coin",
            x: 113,
            y: 608
        }, {
            objname: "coin",
            x: 160,
            y: 655
        }, {
            objname: "coin",
            x: 224,
            y: 672
        }, {
            objname: "coin",
            x: 288,
            y: 672
        }, {
            objname: "coin",
            x: 352,
            y: 672
        }, {
            objname: "coin",
            x: 416,
            y: 672
        }, {
            objname: "coin",
            x: 480,
            y: 689
        }, {
            objname: "coin",
            x: 527,
            y: 736
        }, {
            objname: "ruby",
            x: 544,
            y: 800
        }, {
            objname: "coin",
            x: 527,
            y: 864
        }, {
            objname: "coin",
            x: 480,
            y: 911
        }, {
            objname: "coin",
            x: 416,
            y: 928
        }, {
            objname: "coin",
            x: 352,
            y: 928
        }, {
            objname: "coin",
            x: 288,
            y: 928
        }, {
            objname: "coin",
            x: 224,
            y: 928
        }, {
            objname: "coin",
            x: 158,
            y: 945
        }, {
            objname: "coin",
            x: 111,
            y: 992
        }, {
            objname: "coin",
            x: 94,
            y: 1056
        }, {
            objname: "coin",
            x: 94,
            y: 1120
        }, {
            objname: "mine",
            x: 32,
            y: 800
        }, {
            objname: "mine",
            x: 96,
            y: 800
        }, {
            objname: "mine",
            x: 160,
            y: 800
        }, {
            objname: "mine",
            x: 224,
            y: 800
        }, {
            objname: "mine",
            x: 288,
            y: 800
        }, {
            objname: "mine",
            x: 352,
            y: 800
        }, {
            objname: "mine",
            x: 416,
            y: 800
        }, {
            objname: "mine",
            x: 224,
            y: 1056
        }, {
            objname: "mine",
            x: 288,
            y: 1056
        }, {
            objname: "mine",
            x: 352,
            y: 1056
        }, {
            objname: "mine",
            x: 416,
            y: 1056
        }, {
            objname: "mine",
            x: 480,
            y: 1056
        }, {
            objname: "mine",
            x: 544,
            y: 1056
        }, {
            objname: "mine",
            x: 608,
            y: 1056
        }]
    }, {
        ysize: 560,
        objs: [{
            objname: "coin",
            x: 40,
            y: 80
        }, {
            objname: "coin",
            x: 120,
            y: 80
        }, {
            objname: "coin",
            x: 200,
            y: 80
        }, {
            objname: "coin",
            x: 280,
            y: 80
        }, {
            objname: "coin",
            x: 360,
            y: 80
        }, {
            objname: "coin",
            x: 440,
            y: 80
        }, {
            objname: "coin",
            x: 520,
            y: 80
        }, {
            objname: "coin",
            x: 600,
            y: 80
        }, {
            objname: "coin",
            x: 40,
            y: 160
        }, {
            objname: "coin",
            x: 120,
            y: 160
        }, {
            objname: "coin",
            x: 200,
            y: 160
        }, {
            objname: "coin",
            x: 280,
            y: 160
        }, {
            objname: "coin",
            x: 360,
            y: 160
        }, {
            objname: "coin",
            x: 440,
            y: 160
        }, {
            objname: "coin",
            x: 520,
            y: 160
        }, {
            objname: "coin",
            x: 600,
            y: 160
        }, {
            objname: "mine",
            x: 320,
            y: 240,
            movetype: "cirh",
            radius: 240,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "cirh",
            radius: 240,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 400,
            movetype: "cirh",
            radius: 240,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 480,
            movetype: "cirh",
            radius: 240,
            angle: 180
        }]
    }, {
        ysize: 560,
        objs: [{
            objname: "coin",
            x: 40,
            y: 80
        }, {
            objname: "coin",
            x: 120,
            y: 80
        }, {
            objname: "coin",
            x: 40,
            y: 160
        }, {
            objname: "coin",
            x: 120,
            y: 160
        }, {
            objname: "ruby",
            x: 220,
            y: 120
        }, {
            objname: "ruby",
            x: 320,
            y: 120
        }, {
            objname: "ruby",
            x: 420,
            y: 120
        }, {
            objname: "coin",
            x: 520,
            y: 80
        }, {
            objname: "coin",
            x: 600,
            y: 80
        }, {
            objname: "coin",
            x: 520,
            y: 160
        }, {
            objname: "coin",
            x: 600,
            y: 160
        }, {
            objname: "mine",
            x: 320,
            y: 240,
            movetype: "cirh",
            radius: 240,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 320,
            movetype: "cirh",
            radius: 240,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 400,
            movetype: "cirh",
            radius: 240,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 480,
            movetype: "cirh",
            radius: 240,
            angle: 180
        }]
    }, {
        ysize: 480,
        objs: [{
            objname: "coin",
            x: 40,
            y: 80
        }, {
            objname: "coin",
            x: 120,
            y: 80
        }, {
            objname: "coin",
            x: 200,
            y: 80
        }, {
            objname: "coin",
            x: 280,
            y: 80
        }, {
            objname: "coin",
            x: 360,
            y: 80
        }, {
            objname: "coin",
            x: 440,
            y: 80
        }, {
            objname: "coin",
            x: 520,
            y: 80
        }, {
            objname: "coin",
            x: 600,
            y: 80
        }, {
            objname: "coin",
            x: 40,
            y: 160
        }, {
            objname: "coin",
            x: 120,
            y: 160
        }, {
            objname: "coin",
            x: 200,
            y: 160
        }, {
            objname: "coin",
            x: 280,
            y: 160
        }, {
            objname: "coin",
            x: 360,
            y: 160
        }, {
            objname: "coin",
            x: 440,
            y: 160
        }, {
            objname: "coin",
            x: 520,
            y: 160
        }, {
            objname: "coin",
            x: 600,
            y: 160
        }, {
            objname: "treasure",
            x: 320,
            y: 416
        }]
    }]
}, {
    comment: "level 12 HARDEST!",
    parts: [{
        ysize: 640,
        objs: [{
            objname: "mine",
            x: 32,
            y: 280
        }, {
            objname: "mine",
            x: 80,
            y: 280
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 192,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 144,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 96,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 48,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 48,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 96,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 144,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 192,
            angle: 0
        }, {
            objname: "mine",
            x: 560,
            y: 280
        }, {
            objname: "mine",
            x: 608,
            y: 280
        }, {
            objname: "coin",
            x: 32,
            y: 88
        }, {
            objname: "coin",
            x: 96,
            y: 88
        }, {
            objname: "coin",
            x: 160,
            y: 88
        }, {
            objname: "coin",
            x: 224,
            y: 88
        }, {
            objname: "coin",
            x: 416,
            y: 88
        }, {
            objname: "coin",
            x: 480,
            y: 88
        }, {
            objname: "coin",
            x: 544,
            y: 88
        }, {
            objname: "coin",
            x: 608,
            y: 88
        }, {
            objname: "coin",
            x: 32,
            y: 152
        }, {
            objname: "coin",
            x: 96,
            y: 152
        }, {
            objname: "coin",
            x: 160,
            y: 152
        }, {
            objname: "coin",
            x: 480,
            y: 152
        }, {
            objname: "coin",
            x: 544,
            y: 152
        }, {
            objname: "coin",
            x: 608,
            y: 152
        }, {
            objname: "coin",
            x: 32,
            y: 408
        }, {
            objname: "coin",
            x: 160,
            y: 408
        }, {
            objname: "coin",
            x: 480,
            y: 408
        }, {
            objname: "coin",
            x: 544,
            y: 408
        }, {
            objname: "coin",
            x: 608,
            y: 408
        }, {
            objname: "coin",
            x: 96,
            y: 408
        }, {
            objname: "coin",
            x: 32,
            y: 472
        }, {
            objname: "coin",
            x: 96,
            y: 472
        }, {
            objname: "coin",
            x: 160,
            y: 472
        }, {
            objname: "coin",
            x: 224,
            y: 472
        }, {
            objname: "coin",
            x: 416,
            y: 472
        }, {
            objname: "coin",
            x: 480,
            y: 472
        }, {
            objname: "coin",
            x: 544,
            y: 472
        }, {
            objname: "coin",
            x: 608,
            y: 472
        }]
    }, {
        ysize: 1280,
        objs: [{
            objname: "mine",
            x: 320,
            y: 32,
            movetype: "cirh",
            radius: 288,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 64,
            movetype: "cirh",
            radius: 288,
            angle: 10
        }, {
            objname: "mine",
            x: 320,
            y: 96,
            movetype: "cirh",
            radius: 288,
            angle: 20
        }, {
            objname: "mine",
            x: 320,
            y: 128,
            movetype: "cirh",
            radius: 288,
            angle: 10
        }, {
            objname: "mine",
            x: 320,
            y: 160,
            movetype: "cirh",
            radius: 288,
            angle: 0
        }, {
            objname: "coin",
            x: 226,
            y: 224
        }, {
            objname: "coin",
            x: 290,
            y: 224
        }, {
            objname: "coin",
            x: 354,
            y: 224
        }, {
            objname: "coin",
            x: 418,
            y: 224
        }, {
            objname: "coin",
            x: 226,
            y: 608
        }, {
            objname: "coin",
            x: 290,
            y: 608
        }, {
            objname: "coin",
            x: 354,
            y: 608
        }, {
            objname: "coin",
            x: 418,
            y: 608
        }, {
            objname: "mine",
            x: 320,
            y: 352,
            movetype: "cirh",
            radius: 288,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 384,
            movetype: "cirh",
            radius: 288,
            angle: 190
        }, {
            objname: "mine",
            x: 320,
            y: 416,
            movetype: "cirh",
            radius: 288,
            angle: 200
        }, {
            objname: "mine",
            x: 320,
            y: 448,
            movetype: "cirh",
            radius: 288,
            angle: 190
        }, {
            objname: "mine",
            x: 320,
            y: 480,
            movetype: "cirh",
            radius: 288,
            angle: 180
        }, {
            objname: "coin",
            x: 226,
            y: 544
        }, {
            objname: "coin",
            x: 290,
            y: 544
        }, {
            objname: "coin",
            x: 354,
            y: 544
        }, {
            objname: "coin",
            x: 418,
            y: 544
        }, {
            objname: "coin",
            x: 226,
            y: 288
        }, {
            objname: "coin",
            x: 290,
            y: 288
        }, {
            objname: "coin",
            x: 354,
            y: 288
        }, {
            objname: "coin",
            x: 418,
            y: 288
        }, {
            objname: "mine",
            x: 320,
            y: 672,
            movetype: "cirh",
            radius: 288,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 704,
            movetype: "cirh",
            radius: 288,
            angle: 10
        }, {
            objname: "mine",
            x: 320,
            y: 736,
            movetype: "cirh",
            radius: 288,
            angle: 20
        }, {
            objname: "mine",
            x: 320,
            y: 768,
            movetype: "cirh",
            radius: 288,
            angle: 10
        }, {
            objname: "mine",
            x: 320,
            y: 800,
            movetype: "cirh",
            radius: 288,
            angle: 0
        }, {
            objname: "coin",
            x: 226,
            y: 864
        }, {
            objname: "coin",
            x: 290,
            y: 864
        }, {
            objname: "coin",
            x: 354,
            y: 864
        }, {
            objname: "coin",
            x: 418,
            y: 864
        }, {
            objname: "mine",
            x: 320,
            y: 992,
            movetype: "cirh",
            radius: 288,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 1024,
            movetype: "cirh",
            radius: 288,
            angle: 190
        }, {
            objname: "mine",
            x: 320,
            y: 1056,
            movetype: "cirh",
            radius: 288,
            angle: 200
        }, {
            objname: "mine",
            x: 320,
            y: 1088,
            movetype: "cirh",
            radius: 288,
            angle: 190
        }, {
            objname: "mine",
            x: 320,
            y: 1120,
            movetype: "cirh",
            radius: 288,
            angle: 180
        }, {
            objname: "coin",
            x: 226,
            y: 928
        }, {
            objname: "coin",
            x: 290,
            y: 928
        }, {
            objname: "coin",
            x: 354,
            y: 928
        }, {
            objname: "coin",
            x: 418,
            y: 928
        }]
    }, {
        ysize: 560,
        objs: [{
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 192,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 144,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 96,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 48,
            angle: 180
        }, {
            objname: "mine",
            x: 320,
            y: 280
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 48,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 96,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 144,
            angle: 0
        }, {
            objname: "mine",
            x: 320,
            y: 280,
            movetype: "circ",
            radius: 192,
            angle: 0
        }, {
            objname: "coin",
            x: 608,
            y: 280
        }, {
            objname: "coin",
            x: 598,
            y: 355
        }, {
            objname: "coin",
            x: 569,
            y: 424
        }, {
            objname: "coin",
            x: 524,
            y: 484
        }, {
            objname: "coin",
            x: 116,
            y: 484
        }, {
            objname: "coin",
            x: 71,
            y: 424
        }, {
            objname: "coin",
            x: 42,
            y: 355
        }, {
            objname: "coin",
            x: 32,
            y: 280
        }, {
            objname: "coin",
            x: 42,
            y: 205
        }, {
            objname: "coin",
            x: 71,
            y: 136
        }, {
            objname: "coin",
            x: 116,
            y: 76
        }, {
            objname: "coin",
            x: 524,
            y: 76
        }, {
            objname: "coin",
            x: 569,
            y: 136
        }, {
            objname: "coin",
            x: 598,
            y: 205
        }]
    }, {
        ysize: 320,
        objs: [{
            objname: "treasure",
            x: 320,
            y: 256
        }]
    }]
}];